agents:
  queue: sprites
steps:
  - label: ":golangci-lint: Lint"
    command: golangci-lint run --verbose --timeout 2m
    plugins:
      - docker-compose#v5.12.1:
          config: .buildkite/docker-compose.yml
          run: golangci-lint
          tty: true
  - label: ":go: :test_tube: Test"
    command: .buildkite/scripts/tests.sh
    secrets:
      BUILDKITE_ANALYTICS_TOKEN: SPRITES_SUITE_TOKEN
    plugins:
      - test-collector#v1.11.0:
          files: "*.xml"
          format: "junit"
